//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mawosoft.PowerShell.WindowsSearchManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mawosoft.PowerShell.WindowsSearchManager.resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires administrative privileges..
        /// </summary>
        internal static string AdminRequiredForOperation {
            get {
                return ResourceManager.GetString("AdminRequiredForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interface {0} is not available..
        /// </summary>
        internal static string InterfaceNotAvailable {
            get {
                return ResourceManager.GetString("InterfaceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A: Requires admin rights..
        /// </summary>
        internal static string NA_AdminRequired {
            get {
                return ResourceManager.GetString("NA_AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverrideChildren not supported for default rule set..
        /// </summary>
        internal static string OverrideChildrenNotSupported {
            get {
                return ResourceManager.GetString("OverrideChildrenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned COMObject {0} is null, but no error info is available..
        /// </summary>
        internal static string ReturnedCOMObjectIsNull {
            get {
                return ResourceManager.GetString("ReturnedCOMObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Proxy: Access={0}, Name={1}, PortNumber={2}, BypassLocal={3}, BypassList={4}.
        /// </summary>
        internal static string SetProxy {
            get {
                return ResourceManager.GetString("SetProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///User Agent={0}.
        /// </summary>
        internal static string SetUserAgent {
            get {
                return ResourceManager.GetString("SetUserAgent", resourceCulture);
            }
        }
    }
}
