name: Update Single File Dependencies

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

defaults:
  run:
    shell: pwsh

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

permissions:
  contents: write
  pull-requests: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
        fetch-depth: 1
    - name: Update
      # Both must be set because dotnet-file internally calls gh cli to fetch the changelog.
      env:
        GCM_CREDENTIAL_STORE: cache
        GH_TOKEN: ${{ github.token }}
      id: update
      run: |
        dotnet tool update -g dotnet-file

        [string]$tmpfile = New-TemporaryFile
        dotnet-file update "-c:$tmpfile"

        [string]$content = Get-Content $tmpfile -Raw
        if (-not $content) {
          'No changelog.'
        }
        else {
          Write-Output 'Changelog<<EOF' >>$env:GITHUB_OUTPUT
          Write-Output $content >>$env:GITHUB_OUTPUT
          Write-Output 'EOF' >>$env:GITHUB_OUTPUT
          $content
        }
    - name: Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        base: master
        branch: dotnet-file-sync
        delete-branch: true
        labels: dependencies
        title: Update Single File Dependencies
        body: ${{ steps.update.outputs.Changelog }}
        commit-message: |
          Update Single File Dependencies

          ${{ steps.sync.outputs.Changelog }}
