name: Build gh-pages

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  MSBuildDebugEngine: 1
  MSBUILDLOGTASKINPUTS: 1
  MSBUILDTARGETOUTPUTLOGGING: true
  MSBUILDLOGIMPORTS: 1

jobs:
  gh-pages:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
        fetch-depth: 1
    - name: Setup dotnet (pinned)
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json
    - name: DocFX Build
      run: |
        $ErrorActionPreference = 'Stop'
        $PSNativeCommandUseErrorActionPreference = $true
        dotnet restore
        dotnet build ./docs/docs.msbuildproj --no-restore -c Release
    - name: Upload Binlogs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: DocFX-Binlogs
        path: '**/MSBuild_Logs/*'
    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
