name: Build and Publish Docs Website

on:
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: DotNet Info
      run: dotnet --info
    - name: DocFX Build
      run: |
        . ./build/startNativeExecution.ps1
        Start-NativeExecution { dotnet build ./docs/docs.msbuildproj -c Debug -bl:./Binlogs/build_docfx.binlog }
    - name: Upload Binlogs
      uses: actions/upload-artifact@v3
      with:
        name: DocFX-Binlogs
        path: ./Binlogs/
    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
